### ISSUE TITLE
Starting from an initial mesh estimate

### ISSUE THREAD

**Issue by yyeboah** [ashawkey/Drag3D#1]
Very cool work, in a very short turn-around time! Cheers.

So I see this and naturally wonder how the application scope would grow if one could initialise optimization using an existing mesh. Is this within the current project scope?

**Comment by ashawkey** [comment]
@yyeboah Hi, thanks! Current meshes are generated from the latent space of GET3D (a 3D GAN), which we rely on to perform drag editing. So I think we cannot get any existing mesh to work, but it maybe possible to apply GAN inversion for a specific mesh like cars.
